name: CI/CD Pipeline for Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-files
          path: |
            target/*.jar
            Dockerfile
            docker-compose.yml
            config/**

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-files
          path: ./deploy

      - name: Setup SSH
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Debug: Show files
          echo "Local files:"
          ls -la ./deploy

          # Prepare EC2
          ssh -i key.pem ec2-user@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            rm -rf ~/app
            mkdir -p ~/app/config
          EOF

          # Copy files
          cd deploy
          scp -i ../key.pem \
            *.jar \
            Dockerfile \
            docker-compose.yml \
            ec2-user@${{ secrets.EC2_INSTANCE_IP }}:~/app/

          if [ -d "config" ]; then
            scp -i ../key.pem -r config/* ec2-user@${{ secrets.EC2_INSTANCE_IP }}:~/app/config/
          fi

          # Deploy
          ssh -i ../key.pem ec2-user@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            cd ~/app
            docker-compose down || true
            docker system prune -f
            docker-compose up -d --build
            echo "Waiting for containers to start..."
            sleep 10
            docker ps
            docker logs hello-world-app
          EOF
